# Generated by Django 2.2 on 2019-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Test description for product'),
            preserve_default=False,
        ),
    ]
