# Generated by Django 2.2 on 2019-10-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_orderitem_billing_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['title']},
        ),
    ]
